steps:
  - name: 'hashicorp/terraform:light'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        rm -rf .terraform
        terraform init -reconfigure
        terraform apply -auto-approve
    dir: './tf-scripts'

options:
  logging: CLOUD_LOGGING_ONLY