version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile-client
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./Dockerfile-server
    ports:
      - "5000:5000"